# Generated by Django 4.0.6 on 2022-07-11 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_sal',
            field=models.IntegerField(default=20000),
            preserve_default=False,
        ),
    ]
