# Generated by Django 4.0.6 on 2022-07-11 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapi', '0002_employee_emp_sal'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.CharField(default='123@gmail.com', max_length=40),
        ),
    ]
