# Generated by Django 4.0.6 on 2022-07-12 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=20)),
                ('dept_id', models.IntegerField()),
                ('dept_budget', models.IntegerField()),
                ('dept_employees', models.IntegerField()),
            ],
        ),
    ]
